GET http://localhost:8080/authorize?user&password=1234

###

GET http://localhost:8080/authorize?user=dss&password=1234

###

GET http://localhost:8080/authorize?user=yaroslav&password=12345

###

GET http://localhost:8080/signin.html

###

GET http://localhost:8080/welcome

###

GET http://localhost:8080/read/userProfile

###

GET http://localhost:8080/write/userProfile

###

GET http://localhost:8080/write_or_delete/userProfile

###

http://localhost:8080/hello-user?username=Igor




